spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/StoredProducer
    username: postgres
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082